name: Pre Merge Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build-windows-natives:
    runs-on: windows-latest
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build Windows native DLLs
        shell: cmd
        run: call darkmode-detector\src\main\native\windows\build.bat
      - name: Upload Windows DLLs
        uses: actions/upload-artifact@v4
        with:
          name: windows-natives
          path: darkmode-detector/src/main/resources/nucleus/native/win32-*/
          retention-days: 1

  gradle:
    needs: build-windows-natives
    runs-on: ubuntu-latest
    env:
      GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
      GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Download Windows DLLs
        uses: actions/download-artifact@v4
        with:
          name: windows-natives
          path: darkmode-detector/src/main/resources/nucleus/native/
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Cache Gradle Caches
        uses: gradle/actions/setup-gradle@v4
      - name: Run Gradle tasks
        run: ./gradlew preMerge --continue
